- hosts: localhost
  connection: local
  tasks:
    - include: tasks/ec2/load_groups.yml
      vars:
        - group_name: core
        - group_description: "Core group for all servers"
        - rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
    - include: tasks/ec2/load_ec2_instances.yml
      vars:
        - count: 1
        - group: "core"
        - name: DAWS1
        - size: t2.small
        - image: "{{ami_id_ubuntu_1604}}"
        - vpc_subnet: "{{ec2_vpc_subnet_dev}}"
        - host_groups: "ec2,<TODO: Define main host group if required>"
    - include: tasks/ec2/instance_options.yml
      vars:
        - device: /dev/xvdf
        - volume_name: app
        - add_to_groups: "ec2"
        - volume_size: 10
        - new_volume: true
    - include: tasks/ec2/instance_options.yml
      vars:
        - device: /dev/xvdg
        - volume_name: logs
        - add_to_groups: "ec2"
        - volume_size: 10
        - new_volume: true


- hosts: ec2
  tasks:
    - include: tasks/ec2/mount_volume.yml device=/dev/xvdf dir=/<TODO: Define root directory>
    - include: tasks/ec2/mount_volume.yml device=/dev/xvdg dir=/var/log
    - debug: var=hostvars[inventory_hostname]

