- hosts: localhost
  connection: local
  tasks:
    - name: Add to Load Balancer
      ec2_elb: instance_id={{item.id}} ec2_elbs="{{load_balancer}}" state=present
      with_items: ec2_instances
      when: load_balancer is defined
