- name: load group {{group_name}}
  ec2_group:
    name: "{{group_name}}"
    description: "{{group_description}}"
    vpc_id: "{{group_vpc_id|default(None)}}"
    region: "{{group_region|default('eu-west-1c')}}"
    rules: "{{group_rules}}"
    rules_egress: "{{group_rules_out|default(default_ec2_rules_out)}}"
